// apps/web/src/routes/(protected)/account/profile/+page.svelte
<script lang="ts">
  import Logout from "./_components/logout.svelte";

  const { data } = $props();
</script>

<div class="min-h-dvh pt-24">
  <div
    class="w-full border-b border-dashed px-12 pb-8 text-end text-5xl font-medium tracking-tight lg:px-64"
  >
    Profile
  </div>

  <div class="mx-12 mt-36 space-y-12 text-xl lg:mx-24">
    <div class="tracking-tight">Username: {data.user.username}</div>
    <div class="tracking-tight">Name: {data.user.name}</div>
    <div class="space-y-2">
      <div class="tracking-tight">Logout from current device</div>
      <Logout />
    </div>
  </div>
</div>

// apps/web/src/routes/(protected)/account/profile.tsx
import { createFileRoute } from "@tanstack/react-router";

import { Logout } from "@/components/logout";

export const Route = createFileRoute("/(protected)/account/profile")({
  head: () => ({
    meta: [{ title: "Edit Profile (Beta)" }],
  }),
  component: RouteComponent,
});

function RouteComponent() {
  const { user } = Route.useRouteContext();

  return (
    <div className="pt-24 min-h-dvh">
      <div className="text-5xl font-medium tracking-tight pb-8 text-end border-b border-dashed w-full px-12 lg:px-64">
        Profile
      </div>

      <div className="space-y-12 mx-12 lg:mx-24 text-xl mt-36">
        <div className="tracking-tight">Username: {user.username}</div>
        <div className="tracking-tight">Name: {user.name}</div>
        <div className="space-y-2">
          <div className="tracking-tight">Logout from current device</div>
          <Logout />
        </div>
      </div>
    </div>
  );
}
