// apps/web/src/components/sidebar/header.tsx
import { QuillWriteIcon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { Link } from "@tanstack/react-router";
import { SidebarMenu, SidebarMenuButton, SidebarMenuItem } from "../ui/sidebar";

export const Header = () => {
  return (
    <SidebarMenu>
      <SidebarMenuItem className="w-max">
        <SidebarMenuButton tooltip="MetaPress" className="hover:bg-transparent mt-0.5">
          <Link to="/" className="inline-flex gap-1 items-center">
            <HugeiconsIcon icon={QuillWriteIcon} strokeWidth={2} className="size-5!" />
            <span className="text-base tracking-tight">MetaPress</span>
          </Link>
        </SidebarMenuButton>
      </SidebarMenuItem>
    </SidebarMenu>
  );
};

// apps/web/src/lib/components/sidebar/header.svelte
<script lang="ts">
  import { QuillWriteIcon } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";

  import { SidebarMenu, SidebarMenuButton, SidebarMenuItem } from "../ui/sidebar";
</script>

<SidebarMenu>
  <SidebarMenuItem class="w-max">
    <SidebarMenuButton tooltipContent="MetaPress" class="mt-0.5 hover:bg-transparent">
      <a href="/" class="inline-flex items-center gap-1">
        <HugeiconsIcon icon={QuillWriteIcon} strokeWidth={2} class="size-5!" />
        <span class="text-base tracking-tight">MetaPress</span>
      </a>
    </SidebarMenuButton>
  </SidebarMenuItem>
</SidebarMenu>
