// apps/web/src/components/sidebar/sidebar.tsx
import { Sidebar as SB, SidebarContent, SidebarFooter, SidebarHeader } from "../ui/sidebar";
import { Footer } from "./footer";
import { Header } from "./header";
import { Navbar } from "./navbar";

export const Sidebar = ({
  user,
  ...props
}: React.ComponentProps<typeof SB> & { user: UserSession | null }) => {
  return (
    <SB collapsible="icon" {...props}>
      <SidebarHeader>
        <Header />
      </SidebarHeader>

      <SidebarContent>
        <Navbar user={user} />
      </SidebarContent>

      <SidebarFooter>
        <Footer user={user} />
      </SidebarFooter>
    </SB>
  );
};

// apps/web/src/lib/components/sidebar/index.svelte
<script lang="ts">
  import type { UserSession } from "$lib/auth-client";

  import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader } from "../ui/sidebar";
  import Footer from "./footer.svelte";
  import Header from "./header.svelte";
  import Navbar from "./navbar.svelte";

  const { user }: { user: UserSession } = $props();
</script>

<Sidebar collapsible="icon">
  <SidebarHeader>
    <Header />
  </SidebarHeader>

  <SidebarContent>
    <Navbar />
  </SidebarContent>

  <SidebarFooter>
    <Footer {user} />
  </SidebarFooter>
</Sidebar>
