// apps/web/src/routes/(auth)/reset-password.tsx
import { z } from "zod";
import { createFileRoute } from "@tanstack/react-router";

import { ResetPasswordForm } from "./-components/reset-pass-form";

export const Route = createFileRoute("/(auth)/reset-password")({
  validateSearch: (search) =>
    z
      .object({
        token: z.string(),
      })
      .parse(search),
  head: () => ({
    meta: [{ title: "Reset Password" }],
  }),
  component: RouteComponent,
});

function RouteComponent() {
  const { token } = Route.useSearch();

  return (
    <div className="flex flex-col xl:flex-row gap-16 2xl:gap-24 m-4 xl:m-8 p-8 pt-24 xl:pt-32 min-h-[96dvh] xl:min-h-[94dvh]">
      <div className="space-y-4">
        <div className="text-sm text-primary">RESET PASSWORD</div>
        <div className="text-3xl lg:text-4xl xl:text-5xl tracking-tighter w-xs lg:w-sm xl:w-md">
          Just a reminder that this action can&apos;t be undone. Also, this link is valid only for 1
          hour
        </div>
      </div>
      <div className="xl:w-md">
        <ResetPasswordForm token={token} />
      </div>
    </div>
  );
}

// apps/web/src/routes/(auth)/reset-password/+page.svelte
<script lang="ts">
  import { page } from "$app/state";

  import ResetPasswordForm from "../_components/reset-pass-form.svelte";

  const token = page.url.searchParams.get("token");
  if (!token) {
    throw new Error("Something went wrong");
  }
</script>

<svelte:head>
  <title>Reset Password</title>
</svelte:head>

<div
  class="m-4 flex min-h-[96dvh] flex-col gap-16 p-8 pt-24 xl:m-8 xl:min-h-[94dvh] xl:flex-row xl:pt-32 2xl:gap-24"
>
  <div class="space-y-4">
    <div class="text-primary text-sm">RESET PASSWORD</div>
    <div class="w-xs text-3xl tracking-tighter lg:w-sm lg:text-4xl xl:w-md xl:text-5xl">
      Just a reminder that this action can&apos;t be undone and this link is valid only for 1 hour
    </div>
  </div>
  <div class="xl:w-md">
    <ResetPasswordForm token={token!} />
  </div>
</div>
