// apps/web/src/lib/components/author.svelte
<script lang="ts">
  import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";

  const {
    name,
    username,
    image,
  }: {
    name: string;
    image: string | null | undefined;
    username: string;
  } = $props();
</script>

<div class="flex items-center gap-2.5">
  <Avatar>
    <AvatarImage src={image ?? undefined} alt={name} />
    <AvatarFallback>{name[0].toUpperCase() || "M"}</AvatarFallback>
  </Avatar>
  <a href="/{username}" class="max-w-3xs truncate font-medium tracking-tight hover:animate-pulse">
    {name}
  </a>
</div>

// apps/web/src/components/author.tsx
import { Link } from "@tanstack/react-router";

import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";

export const Author = ({
  name,
  image,
  username,
}: {
  name: string;
  image: string | null | undefined;
  username: string;
}) => {
  return (
    <div className="flex gap-2.5 items-center">
      <Avatar>
        <AvatarImage src={image ?? undefined} alt={name} />
        <AvatarFallback>{name[0].toUpperCase() || "M"}</AvatarFallback>
      </Avatar>
      <Link
        to="/$username"
        params={{ username }}
        className="font-medium max-w-3xs truncate tracking-tight hover:animate-pulse"
      >
        {name}
      </Link>
    </div>
  );
};
