// apps/web/src/lib/components/combobox.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button/index";
  import { cn } from "$lib/utils";
  import { Check, UnfoldMoreIcon } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";

  import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandInput,
    CommandItem,
    CommandList,
  } from "./ui/command";
  import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover";

  let {
    array,
    placeholder,
    value = $bindable(),
    loading = false,
  }: {
    array: string[];
    placeholder: string;
    value: string;
    loading?: boolean;
  } = $props();

  let open = $state(false);
</script>

<Popover bind:open>
  <PopoverTrigger>
    {#snippet child({ props })}
      <Button
        {...props}
        variant="outline"
        class="w-50 justify-between"
        role="combobox"
        aria-expanded={open}
        disabled={loading}
      >
        {value || placeholder}
        <HugeiconsIcon icon={UnfoldMoreIcon} class="opacity-50" />
      </Button>
    {/snippet}
  </PopoverTrigger>
  <PopoverContent class="w-50 p-0">
    <Command>
      <CommandInput placeholder={`Search ${placeholder}`} class="h-9" />
      <CommandList>
        <CommandEmpty>Try a different search</CommandEmpty>
        <CommandGroup>
          {#each array as item}
            <CommandItem
              value={item}
              onSelect={() => {
                value = item === value ? "" : item;
                open = false;
              }}
            >
              {item}
              <HugeiconsIcon
                icon={Check}
                class={cn("ml-auto", value === item ? "opacity-100" : "opacity-0")}
              />
            </CommandItem>
          {/each}
        </CommandGroup>
      </CommandList>
    </Command>
  </PopoverContent>
</Popover>

// apps/web/src/components/combobox.tsx
import { Check, UnfoldMoreIcon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { Button } from "./ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "./ui/command";
import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover";

export const Combobox = ({
  array,
  placeholder,
  value,
  setValue,
  loading,
}: {
  array: Array<string>;
  placeholder: string;
  value: string;
  setValue: (value: string) => void;
  loading: boolean;
}) => {
  const [open, setOpen] = useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger
        render={(props) => (
          <Button
            {...props}
            variant="outline"
            role="combobox"
            aria-expanded={open}
            className="w-50 justify-between"
            disabled={loading}
          >
            {value ? array.find((item) => item === value) : placeholder}
            <HugeiconsIcon icon={UnfoldMoreIcon} className="opacity-50" />
          </Button>
        )}
      ></PopoverTrigger>
      <PopoverContent className="w-50 p-0">
        <Command>
          <CommandInput placeholder={`Search ${placeholder}`} className="h-9" />
          <CommandList>
            <CommandEmpty>Try a different search</CommandEmpty>
            <CommandGroup>
              {array.map((item) => (
                <CommandItem
                  key={item}
                  value={item}
                  onSelect={(currentValue) => {
                    setValue(currentValue === value ? "" : currentValue);
                    setOpen(false);
                  }}
                >
                  {item}
                  <HugeiconsIcon
                    icon={Check}
                    className={cn("ml-auto", value === item ? "opacity-100" : "opacity-0")}
                  />
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};
