// apps/web/src/routes/(protected)/[username]/[blogid]/_components/comment.svelte
<script lang="ts">
  import { show } from "$lib/hooks/alert-dialog.svelte";
  import { orpc } from "$lib/orpc";
  import { getFirstZodError } from "$lib/utils";
  import { MessageSquareText, Trash2 } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";
  import type { BlogComment } from "@metapress/contracts/comments";
  import { createMutation } from "@tanstack/svelte-query";
  import { toast } from "svelte-sonner";
  import { ZodError } from "zod";

  import { Avatar, AvatarFallback, AvatarImage } from "../../../../../lib/components/ui/avatar";
  import { Button } from "../../../../../lib/components/ui/button";
  import { Textarea } from "../../../../../lib/components/ui/textarea";

  const {
    blogId,
    comments,
    isAuthor,
    username,
  }: {
    blogId: string;
    comments: BlogComment[];
    isAuthor: boolean;
    username: string;
  } = $props();

  let comment = $state("");
  let loading = $state(false);
  let commentsList = $derived(comments);

  const createCommentMutation = createMutation(() => orpc.comment.create.mutationOptions());

  const deleteCommentMutation = createMutation(() => orpc.comment.delete.mutationOptions());

  const handleAddComment = async () => {
    loading = true;
    try {
      const newComment = await createCommentMutation.mutateAsync({ blogId, content: comment });
      comment = "";
      commentsList = [...commentsList, newComment];
    } catch (error) {
      if (error instanceof ZodError) {
        toast.error(getFirstZodError(error));
      } else if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    } finally {
      loading = false;
    }
  };

  const handleDeleteComment = async (blogIdX: string, commentX: BlogComment) => {
    try {
      await deleteCommentMutation.mutateAsync({ commentId: commentX.id, blogId: blogIdX });
      commentsList = commentsList.filter((c) => c.id !== commentX.id);
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    }
  };
</script>

<div class="w-4/5 space-y-6 tracking-tight text-balance">
  <div class="relative flex flex-col gap-2">
    <Textarea
      name="comment"
      id="comment"
      placeholder="Add a comment..."
      class="min-h-32 resize-none"
      maxlength={100}
      disabled={loading}
      bind:value={comment}
    />
    <span class="text-muted-foreground absolute right-4 bottom-12 text-xs tracking-tight">
      {comment.length}/100
    </span>
    <div class="flex justify-end gap-2.5 sm:gap-4">
      <Button size="sm" onclick={handleAddComment} disabled={loading || !comment.trim()}>
        {#if loading}
          ...
        {:else}
          Comment <HugeiconsIcon icon={MessageSquareText} />
        {/if}
      </Button>
    </div>
  </div>

  {#each commentsList as c}
    <div class="border-input bg-input/20 flex justify-between rounded-xl border p-4">
      <div class="flex gap-3">
        <a href={`/${c.authorUsername}`} class="relative h-8 w-8 overflow-hidden rounded-full">
          <Avatar>
            <AvatarImage src={c.authorImage || undefined} alt={c.authorName} />
            <AvatarFallback>{c.authorName[0].toUpperCase() || "M"}</AvatarFallback>
          </Avatar>
        </a>
        <div class="flex flex-col gap-0.5">
          <a
            href={`/${c.authorUsername}`}
            class="line-clamp-1 w-fit text-sm font-medium hover:animate-pulse"
          >
            {c.authorName}
          </a>
          <span class="text-sm text-neutral-400">
            {new Intl.DateTimeFormat("en-US", {
              month: "short",
              day: "2-digit",
              year: "numeric",
              hour: "numeric",
              minute: "numeric",
              hour12: true,
            }).format(new Date(c.createdAt))}
          </span>
          <p class="mt-4">{c.content}</p>
        </div>
      </div>
      {#if isAuthor || c.authorUsername === username}
        <HugeiconsIcon
          icon={Trash2}
          size={16}
          class="mt-0.5 mr-0.5 cursor-pointer stroke-red-600"
          onclick={() =>
            show({
              title: "Delete comment?",
              description: c.content,
              actionLabel: "Delete",
              onConfirm: () => handleDeleteComment(blogId, c),
            })}
        />
      {/if}
    </div>
  {/each}
</div>

// apps/web/src/components/comment.tsx
import { MessageSquareText, Trash2 } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { Link } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { ZodError } from "zod";
import { getFirstZodError } from "@/lib/utils";
import { createComment, deleteComment } from "@/server/comment/comment.controller";
import { useAlertDialog } from "./providers/alert-provider";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { Button } from "./ui/button";
import { Textarea } from "./ui/textarea";

export const Comment = ({
  blogId,
  comments,
  isAuthor,
  username,
}: {
  blogId: string;
  comments: Array<BlogComment>;
  isAuthor: boolean;
  username: string;
}) => {
  const { show } = useAlertDialog();
  const [comment, setComment] = useState("");
  const [loading, setLoading] = useState(false);
  const [commentsList, setCommentsList] = useState(comments);

  const handleAddComment = async () => {
    setLoading(true);
    try {
      const newComment = await createComment({ data: { blogId, content: comment } });
      setComment("");
      setCommentsList((prev) => [...prev, newComment]);
    } catch (error) {
      if (error instanceof ZodError) {
        toast.error(getFirstZodError(error));
      } else if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteComment = async (blogIdX: string, commentX: BlogComment) => {
    try {
      await deleteComment({ data: { commentId: commentX.id, blogId: blogIdX } });
      setCommentsList((prev) => prev.filter((c) => c.id !== commentX.id));
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    }
  };

  return (
    <div className="w-4/5 space-y-6 tracking-tight text-balance">
      <div className="relative flex flex-col gap-2">
        <Textarea
          name="comment"
          id="comment"
          placeholder="Add a comment..."
          className="resize-none min-h-32"
          maxLength={100}
          disabled={loading}
          onChange={(e) => setComment(e.target.value)}
          value={comment}
        />
        <span className="absolute bottom-12 right-4 text-xs tracking-tight text-muted-foreground">
          {comment.length}/100
        </span>
        <div className="flex justify-end gap-2.5 sm:gap-4">
          <Button size="sm" onClick={handleAddComment} disabled={loading || !comment.trim()}>
            {loading ? (
              "..."
            ) : (
              <>
                Comment <HugeiconsIcon icon={MessageSquareText} />
              </>
            )}
          </Button>
        </div>
      </div>

      {commentsList.map((c) => (
        <div
          key={c.id}
          className="flex justify-between p-4 border border-input rounded-xl bg-input/20"
        >
          <div className="flex gap-3">
            <Link
              to="/$username"
              params={{ username: c.authorUsername }}
              className="relative w-8 h-8 rounded-full overflow-hidden"
            >
              <Avatar>
                <AvatarImage src={c.authorImage || undefined} alt={c.authorName} />
                <AvatarFallback>{c.authorName[0].toUpperCase() || "M"}</AvatarFallback>
              </Avatar>
            </Link>
            <div className="flex flex-col gap-0.5">
              <Link
                to="/$username"
                params={{ username: c.authorUsername }}
                className="font-medium line-clamp-1 hover:animate-pulse text-sm w-fit"
              >
                {c.authorName}
              </Link>
              <span className="text-sm text-neutral-400">
                {new Intl.DateTimeFormat("en-US", {
                  month: "short",
                  day: "2-digit",
                  year: "numeric",
                  hour: "numeric",
                  minute: "numeric",
                  hour12: true,
                }).format(new Date(c.createdAt))}
              </span>
              <p className="mt-4">{c.content}</p>
            </div>
          </div>
          {(isAuthor || c.authorUsername === username) && (
            <HugeiconsIcon
              icon={Trash2}
              size={16}
              className="cursor-pointer stroke-red-600 mt-0.5 mr-0.5"
              onClick={() =>
                show({
                  title: "Delete comment?",
                  description: c.content,
                  actionLabel: "Delete",
                  onConfirm: () => handleDeleteComment(blogId, c),
                })
              }
            />
          )}
        </div>
      ))}
    </div>
  );
};
