// apps/web/src/routes/(protected)/[username]/[blogid]/_components/edit-delete.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { show } from "$lib/hooks/alert-dialog.svelte";
  import { orpc } from "$lib/orpc";
  import { cn } from "$lib/utils";
  import { PencilLine, Trash2 } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";
  import { createMutation } from "@tanstack/svelte-query";
  import { toast } from "svelte-sonner";

  import { Button } from "../../../../../lib/components/ui/button";

  const {
    title,
    blogId,
    isMobile = false,
  }: { title: string; blogId: string; isMobile?: boolean } = $props();

  const deleteBlogMutation = createMutation(() => orpc.blog.delete.mutationOptions());

  const handleDeleteBlog = async () => {
    const toastId = toast.loading("Deleting...");

    try {
      await deleteBlogMutation.mutateAsync({ blogId });

      goto("/browse", { replaceState: true, invalidate: ["/api/blogs"] });
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    } finally {
      toast.dismiss(toastId);
    }
  };
</script>

<div class={cn(isMobile ? "block lg:hidden" : "hidden lg:block", "mt-3 space-x-4")}>
  <Button
    onclick={() => {
      show({
        title: "Edit this blog?",
        description: `Title: ${title}`,
        actionLabel: "Edit",
        onConfirm: () => goto(`/edit-blog/${blogId}`),
      });
    }}
  >
    <HugeiconsIcon icon={PencilLine} /> Edit
  </Button>
  <Button
    variant="destructive"
    onclick={() =>
      show({
        title: "Delete this blog?",
        actionLabel: "Delete",
        onConfirm: handleDeleteBlog,
      })}
  >
    <HugeiconsIcon icon={Trash2} />
  </Button>
</div>

// apps/web/src/components/edit-delete.tsx
import { toast } from "sonner";
import { HugeiconsIcon } from "@hugeicons/react";
import { useRouter } from "@tanstack/react-router";
import { PencilLine, Trash2 } from "@hugeicons/core-free-icons";

import { Button } from "./ui/button";
import { useAlertDialog } from "./providers/alert-provider";
import { cn } from "@/lib/utils";
import { deleteBlog } from "@/server/blog/blog.controller";

export const EditDelete = ({
  blogId,
  isMobile = false,
}: {
  blogId: string;
  isMobile?: boolean;
}) => {
  const router = useRouter();
  const { show } = useAlertDialog();

  const handleDeleteBlog = async () => {
    const toastId = toast.loading("Deleting...");

    try {
      await deleteBlog({ data: { blogId } });

      router.navigate({ to: "/", replace: true });
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    } finally {
      toast.dismiss(toastId);
    }
  };

  return (
    <div className={cn(isMobile ? "block lg:hidden" : "hidden lg:block", "space-x-4 mt-2")}>
      <Button
        onClick={() => {
          show({
            title: "Edit this blog?",
            description: `ID: ${blogId}`,
            actionLabel: "Edit",
            onConfirm: () =>
              router.navigate({ to: "/edit-blog/$blogid", params: { blogid: blogId } }),
          });
        }}
      >
        <HugeiconsIcon icon={PencilLine} /> Edit
      </Button>
      <Button
        variant="destructive"
        onClick={() =>
          show({
            title: "Delete this blog?",
            actionLabel: "Delete",
            onConfirm: handleDeleteBlog,
          })
        }
      >
        <HugeiconsIcon icon={Trash2} />
      </Button>
    </div>
  );
};
