// apps/web/src/lib/components/user-grid.svelte
<script lang="ts">
  import { Image } from "@unpic/svelte";

  const { blogs } = $props();
</script>

<div class="grid grid-cols-3 gap-1 overflow-hidden lg:rounded-4xl lg:border 2xl:grid-cols-4">
  {#each blogs as { id, title, cover, author }}
    <div class="group relative flex aspect-square flex-col justify-end overflow-hidden outline">
      <a href="/{author.username}/{id}" class="relative block h-full">
        <Image
          src={cover}
          alt={title}
          layout="fullWidth"
          priority={false}
          class="aspect-square cursor-pointer object-cover"
        />
        <div
          class="absolute inset-0 line-clamp-3 flex w-full translate-y-8 items-center justify-center gap-2 px-2 text-center text-lg text-balance opacity-0 backdrop-blur-xl transition-all duration-200 group-hover:translate-y-0 group-hover:bg-black/20 group-hover:opacity-100"
        >
          {title}
        </div>
      </a>
    </div>
  {/each}
</div>

// apps/web/src/components/user-grid.tsx
import { Image } from "@unpic/react";
import { Link } from "@tanstack/react-router";

export const UserGrid = ({ blogs }: { blogs: Array<Blog> }) => {
  return (
    <div className="grid grid-cols-3 2xl:grid-cols-4 gap-1 lg:border lg:rounded-4xl overflow-hidden">
      {blogs.map(({ id, title, cover, author }) => {
        return (
          <div
            key={id}
            className="relative flex flex-col aspect-square justify-end outline group overflow-hidden"
          >
            <Link
              to="/$username/$blogid"
              params={{ username: author.username, blogid: id }}
              className="relative block h-full"
            >
              <Image
                src={cover}
                alt={title}
                layout="fullWidth"
                priority={false}
                className="cursor-pointer object-cover aspect-square"
              />
              <div className="absolute inset-0 flex justify-center items-center gap-2 opacity-0 group-hover:opacity-100 w-full text-center line-clamp-3 transition-all duration-200 translate-y-8 group-hover:translate-y-0 backdrop-blur-xl group-hover:bg-black/20 text-lg text-balance px-2">
                {title}
              </div>
            </Link>
          </div>
        );
      })}
    </div>
  );
};
