// apps/web/src/routes/about.tsx
import { MessageMultiple01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Image } from "@unpic/react";
import { HorizontalList } from "@/components/horizontal-list";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [{ title: "About" }],
  }),
  component: RouteComponent,
});

const myStepsList = [
  {
    image: "/images/creative-writing.jpg",
    tag: "STORYTELLING FIRST",
    title: "Writing & Creativity",
    content:
      "Every great blog begins with an idea. I focus on crafting authentic stories, thoughtful insights, and creative perspectives that connect with readers. From brainstorming to publishing — every word matters here.",
  },
  {
    image: "/images/content-strategy.jpg",
    tag: "STRATEGY MATTERS",
    title: "Content Planning",
    content:
      "Behind every post is a plan. I create content that’s not only engaging but also meaningful — blending SEO strategy, readability, and originality to reach the right audience at the right time.",
  },
  {
    image: "/images/testing-feedback.jpg",
    tag: "RESEARCH & FEEDBACK",
    title: "Testing & Refining",
    content:
      "Before hitting publish, every piece goes through feedback loops and fine-tuning. I listen to our readers, analyze what works, and continuously evolve to keep our content valuable and relevant.",
  },
  {
    image: "/images/community.jpg",
    tag: "READERS FIRST",
    title: "Community",
    content:
      "A blog is more than posts — it’s people. I aim to build a community of readers and writers who share ideas, stories, and support. Your comments and voices are what keep this space alive.",
  },
  {
    image: "/images/growth-analytics.jpg",
    tag: "CONTINUOUS GROWTH",
    title: "Learning & Evolving",
    content:
      "The digital world changes fast, and so do I. I experiment, learn from analytics, and adapt to trends without losing our voice. Growth isn’t just numbers — it’s improvement in every post we share.",
  },
];

const myTakesList = [
  {
    image: "/images/vercel.png",
    title: "Vercel",
  },
  {
    image: "/images/redis.png",
    title: "Redis",
  },
  {
    image: "/images/docker.png",
    title: "Docker",
  },
  {
    image: "/images/cloudinary.png",
    title: "Cloudinary",
  },
  {
    image: "/images/better-auth.webp",
    title: "Better Auth",
  },
  {
    image: "/images/neondb.webp",
    title: "Neon Database",
  },
  {
    image: "/images/drizzleorm.jpeg",
    title: "Drizzle ORM",
  },
  {
    image: "/images/shadcnui.webp",
    title: "Shadcn UI",
  },
];

function RouteComponent() {
  return (
    <section className="space-y-16 mt-8">
      <div className="flex flex-col lg:flex-row justify-between gap-16 lg:gap-0 p-6 md:p-12 mb-0">
        <div className="space-y-2 font-medium">
          <span className="text-sm tracking-tight text-primary">MY STEPS</span>
          <div className="text-5xl xl:text-6xl tracking-tighter">
            My creative workflow
            <br />
            it&apos;s not just a vision.
          </div>
        </div>
        <div className="space-y-4 md:space-y-8">
          <div className="w-3xs xl:w-xs text-balance tracking-tight text-primary">
            "I find my work fulfilling when insight, timing, and authenticity come together"
          </div>
          <span className="text-sm font-semibold">DHRUV JANGID</span>
        </div>
      </div>
      <HorizontalList data={myStepsList} />

      <div className="flex flex-col lg:flex-row overflow-hidden px-6 md:px-12">
        <div className="relative aspect-square w-full lg:w-1/2 border rounded-xl overflow-hidden">
          <Image
            src="/images/creativity-process.jpg"
            alt="Creativity Process Image"
            layout="fullWidth"
            className="object-cover sepia-50"
          />
        </div>
        <div className="flex flex-col justify-center p-4 2xl:p-0 2xl:pl-16 gap-2 lg:gap-4 w-full lg:w-1/2">
          <div className="text-sm">KNOW HOW</div>
          <div className="text-6xl xl:text-7xl leading-14 xl:leading-16 tracking-tighter">
            <div>Creativity</div>
            <div>and Innovation</div>
            <div>built-in.</div>
          </div>
          <div className="leading-snug max-w-sm my-2">
            From the first spark of an idea to the final published piece, creativity drives
            everything I do. Each blog post is crafted through exploration, design, and a touch of
            innovation — blending storytelling with modern digital tools. I believe in
            experimenting, learning, and evolving with every article I write.
          </div>
          <Link to="/contact" className="w-max">
            <Button size="lg">
              <HugeiconsIcon icon={MessageMultiple01Icon} />
              Contact Us
            </Button>
          </Link>
        </div>
      </div>

      <Separator />

      <div className="flex flex-col lg:flex-row justify-between gap-16 lg:gap-0 px-6 md:px-12">
        <div className="space-y-2 font-medium">
          <span className="text-sm tracking-tight text-orange-500">MY TAKES</span>
          <div className="text-5xl xl:text-6xl tracking-tighter">
            Not just an IDE,
            <br />
            but a big family.
          </div>
        </div>
        <div className="space-y-4 md:space-y-8">
          <div className="w-3xs xl:w-xs text-balance tracking-tight text-orange-500">
            "The real magic happens when insight meets timing — and everything feels true to who I
            am"
          </div>
          <span className="text-sm font-semibold">DHRUV JANGID</span>
        </div>
      </div>

      <HorizontalList data={myTakesList} imageOnly />

      <div className="flex flex-col lg:flex-row items-end gap-4 w-full overflow-hidden">
        <Image
          src="/images/left.jpg"
          alt="Pencil"
          layout="fullWidth"
          className="object-cover w-full h-96 xl:h-132 2xl:h-172 xl:w-7/12 rounded-4xl rounded-l-none border border-l-0 sepia-50 brightness-90"
        />
        <Image
          src="/images/right.jpg"
          alt="Pencils"
          layout="fullWidth"
          className="object-cover w-2/3 h-64 xl:h-96 2xl:h-124 xl:w-5/12 rounded-4xl rounded-r-none border border-r-0 sepia-50 brightness-90 contrast-125"
        />
      </div>

      <div className="flex flex-col xl:flex-row justify-between gap-16 xl:gap-0 p-4 xl:px-12 xl:py-36">
        <div className="space-y-36 xl:space-y-24">
          <div className="relative">
            <span className="text-8xl xl:text-[12rem] font-light leading-0">&ldquo;</span>
            <span className="absolute -top-10 xl:-top-16 left-9 xl:left-15 xl:w-3xl text-2xl xl:text-4xl font-medium tracking-tighter">
              We&apos;re always exploring new ideas
            </span>
            <span className="absolute -top-2 xl:-top-5.5 left-0 w-xs xl:w-2xl text-2xl xl:text-4xl font-medium tracking-tighter">
              and creative approaches — pushing boundaries to make every story smarter, fresher, and
              more meaningful.
            </span>
          </div>
          <div className="inline-flex">
            <div className="relative aspect-3/4 w-24">
              <Image
                src="/images/me.png"
                alt="Me"
                layout="fullWidth"
                className="object-cover rounded-xl border sepia-50"
              />
            </div>
            <div className="pl-4 space-y-2">
              <div className="text-orange-500 text-sm tracking-tight">MetaPress</div>
              <div>
                <div className="text-2xl font-medium tracking-tighter">Dhruv Jangid</div>
                <div className="tracking-tight">CEO & Founder</div>
              </div>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-8 xl:gap-24 xl:-mt-18 xl:pr-16">
          <div className="space-y-4 xl:space-y-8 border-b pb-12 xl:pb-24">
            <div className="flex gap-4 xl:gap-8">
              <span className="text-3xl xl:text-4xl leading-7 tracking-tight font-semibold">
                23K
              </span>
              <div className="flex flex-col leading-4">
                <span>Daily</span>
                <span>Readers</span>
              </div>
            </div>
            <div className="text-sm max-w-3xs text-balance">
              Our growing community of readers who engage with fresh stories and insights every day.
            </div>
          </div>
          <div className="space-y-4 xl:space-y-8 border-b pb-12 xl:pb-24">
            <div className="flex gap-4 xl:gap-8">
              <span className="text-3xl xl:text-4xl leading-7 tracking-tight font-semibold">
                38K
              </span>
              <div className="flex flex-col leading-4">
                <span>Words</span>
                <span>Published</span>
              </div>
            </div>
            <div className="text-sm max-w-3xs text-balance">
              From deep dives to creative essays — a reflection of our passion for storytelling and
              sharing ideas.
            </div>
          </div>
          <div className="space-y-4 xl:space-y-8 border-b pb-12 xl:pb-24">
            <div className="flex gap-4 xl:gap-8">
              <span className="text-3xl xl:text-4xl leading-7 tracking-tight font-semibold">
                85%
              </span>
              <div className="flex flex-col leading-4">
                <span>Original</span>
                <span>Content</span>
              </div>
            </div>
            <div className="text-sm max-w-3xs text-balance">
              Most of our posts are built from authentic experiences, thoughts, and perspectives —
              no AI fluff, just real voices.
            </div>
          </div>
          <div className="space-y-4 xl:space-y-8 border-b pb-12 xl:pb-24">
            <div className="flex gap-4 xl:gap-8">
              <span className="text-3xl xl:text-4xl leading-7 tracking-tight font-semibold">
                168
              </span>
              <div className="flex flex-col leading-4">
                <span>Collaborators</span>
                <span>& Writers</span>
              </div>
            </div>
            <div className="text-sm max-w-3xs text-balance">
              A vibrant network of contributors, editors, and creatives shaping our platform
              together.
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// apps/web/src/routes/(non-protected)/about/+page.svelte
<script lang="ts">
  import HorizontalList from "$lib/components/horizontal-list.svelte";
  import { Button } from "$lib/components/ui/button";
  import { Separator } from "$lib/components/ui/separator";
  import { MessageMultiple01Icon } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";
  import { Image } from "@unpic/svelte";

  import { MyStepsList } from "./_constants/steps-list";
  import { MyTakesList } from "./_constants/takes-list";
</script>

<svelte:head>
  <title>About</title>
</svelte:head>

<section class="mt-8 space-y-16">
  <div class="mb-0 flex flex-col justify-between gap-16 p-6 md:p-12 lg:flex-row lg:gap-0">
    <div class="space-y-2 font-medium">
      <span class="text-primary text-sm tracking-tight">MY STEPS</span>
      <div class="text-5xl tracking-tighter xl:text-6xl">
        My creative workflow
        <br />
        it&apos;s not just a vision.
      </div>
    </div>
    <div class="space-y-4 md:space-y-8">
      <div class="text-primary w-3xs tracking-tight text-balance xl:w-xs">
        "I find my work fulfilling when insight, timing, and authenticity come together"
      </div>
      <span class="text-sm font-semibold">DHRUV JANGID</span>
    </div>
  </div>
  <HorizontalList data={MyStepsList} />

  <div class="flex flex-col overflow-hidden px-6 md:px-12 lg:flex-row">
    <div class="relative aspect-square w-full overflow-hidden rounded-xl border lg:w-1/2">
      <Image
        src="/images/creativity-process.jpg"
        alt="Creativity Process Image"
        layout="fullWidth"
        class="object-cover sepia-50"
      />
    </div>
    <div class="flex w-full flex-col justify-center gap-2 p-4 lg:w-1/2 lg:gap-4 2xl:p-0 2xl:pl-16">
      <div class="text-sm">KNOW HOW</div>
      <div class="text-6xl leading-14 tracking-tighter xl:text-7xl xl:leading-16">
        <div>Creativity</div>
        <div>and Innovation</div>
        <div>built-in.</div>
      </div>
      <div class="my-2 max-w-sm leading-snug">
        From the first spark of an idea to the final published piece, creativity drives everything I
        do. Each blog post is crafted through exploration, design, and a touch of innovation —
        blending storytelling with modern digital tools. I believe in experimenting, learning, and
        evolving with every article I write.
      </div>
      <a href="/contact" class="w-max">
        <Button size="lg">
          <HugeiconsIcon icon={MessageMultiple01Icon} />
          Contact Us
        </Button>
      </a>
    </div>
  </div>

  <Separator />

  <div class="flex flex-col justify-between gap-16 px-6 md:px-12 lg:flex-row lg:gap-0">
    <div class="space-y-2 font-medium">
      <span class="text-sm tracking-tight text-orange-500">MY TAKES</span>
      <div class="text-5xl tracking-tighter xl:text-6xl">
        Not just an IDE,
        <br />
        but a big family.
      </div>
    </div>
    <div class="space-y-4 md:space-y-8">
      <div class="w-3xs tracking-tight text-balance text-orange-500 xl:w-xs">
        "The real magic happens when insight meets timing — and everything feels true to who I am"
      </div>
      <span class="text-sm font-semibold">DHRUV JANGID</span>
    </div>
  </div>

  <HorizontalList data={MyTakesList} imageOnly />

  <div class="flex w-full flex-col items-end gap-4 overflow-hidden lg:flex-row">
    <Image
      src="/images/left.jpg"
      alt="Pencil"
      layout="fullWidth"
      class="h-96 w-full rounded-4xl rounded-l-none border border-l-0 object-cover brightness-90 sepia-50 xl:h-132 xl:w-7/12 2xl:h-172"
    />
    <Image
      src="/images/right.jpg"
      alt="Pencils"
      layout="fullWidth"
      class="h-64 w-2/3 rounded-4xl rounded-r-none border border-r-0 object-cover brightness-90 contrast-125 sepia-50 xl:h-96 xl:w-5/12 2xl:h-124"
    />
  </div>

  <div class="flex flex-col justify-between gap-16 p-4 xl:flex-row xl:gap-0 xl:px-12 xl:py-36">
    <div class="space-y-36 xl:space-y-24">
      <div class="relative">
        <span class="text-8xl leading-0 font-light xl:text-[12rem]">&ldquo;</span>
        <span
          class="absolute -top-10 left-9 text-2xl font-medium tracking-tighter xl:-top-16 xl:left-15 xl:w-3xl xl:text-4xl"
        >
          We&apos;re always exploring new ideas
        </span>
        <span
          class="absolute -top-2 left-0 w-xs text-2xl font-medium tracking-tighter xl:-top-5.5 xl:w-2xl xl:text-4xl"
        >
          and creative approaches — pushing boundaries to make every story smarter, fresher, and
          more meaningful.
        </span>
      </div>
      <div class="inline-flex">
        <div class="relative aspect-3/4 w-24">
          <Image
            src="/images/me.png"
            alt="Me"
            layout="fullWidth"
            class="rounded-xl border object-cover sepia-50"
          />
        </div>
        <div class="space-y-2 pl-4">
          <div class="text-sm tracking-tight text-orange-500">MetaPress</div>
          <div>
            <div class="text-2xl font-medium tracking-tighter">Dhruv Jangid</div>
            <div class="tracking-tight">CEO & Founder</div>
          </div>
        </div>
      </div>
    </div>
    <div class="grid grid-cols-2 gap-8 xl:-mt-18 xl:gap-24 xl:pr-16">
      <div class="space-y-4 border-b pb-12 xl:space-y-8 xl:pb-24">
        <div class="flex gap-4 xl:gap-8">
          <span class="text-3xl leading-7 font-semibold tracking-tight xl:text-4xl"> 23K </span>
          <div class="flex flex-col leading-4">
            <span>Daily</span>
            <span>Readers</span>
          </div>
        </div>
        <div class="max-w-3xs text-sm text-balance">
          Our growing community of readers who engage with fresh stories and insights every day.
        </div>
      </div>
      <div class="space-y-4 border-b pb-12 xl:space-y-8 xl:pb-24">
        <div class="flex gap-4 xl:gap-8">
          <span class="text-3xl leading-7 font-semibold tracking-tight xl:text-4xl"> 38K </span>
          <div class="flex flex-col leading-4">
            <span>Words</span>
            <span>Published</span>
          </div>
        </div>
        <div class="max-w-3xs text-sm text-balance">
          From deep dives to creative essays — a reflection of our passion for storytelling and
          sharing ideas.
        </div>
      </div>
      <div class="space-y-4 border-b pb-12 xl:space-y-8 xl:pb-24">
        <div class="flex gap-4 xl:gap-8">
          <span class="text-3xl leading-7 font-semibold tracking-tight xl:text-4xl"> 85% </span>
          <div class="flex flex-col leading-4">
            <span>Original</span>
            <span>Content</span>
          </div>
        </div>
        <div class="max-w-3xs text-sm text-balance">
          Most of our posts are built from authentic experiences, thoughts, and perspectives — no AI
          fluff, just real voices.
        </div>
      </div>
      <div class="space-y-4 border-b pb-12 xl:space-y-8 xl:pb-24">
        <div class="flex gap-4 xl:gap-8">
          <span class="text-3xl leading-7 font-semibold tracking-tight xl:text-4xl"> 168 </span>
          <div class="flex flex-col leading-4">
            <span>Collaborators</span>
            <span>& Writers</span>
          </div>
        </div>
        <div class="max-w-3xs text-sm text-balance">
          A vibrant network of contributors, editors, and creatives shaping our platform together.
        </div>
      </div>
    </div>
  </div>
</section>
