// apps/web/src/routes/(protected)/feed/+page.svelte
<script lang="ts">
  import Grid from "$lib/components/grid.svelte";
  import { Skeleton } from "$lib/components/ui/skeleton";
  import { orpc } from "$lib/orpc";
  import { createQuery } from "@tanstack/svelte-query";

  const blogs = createQuery(() => orpc.blog.getFeed.queryOptions());
</script>

<div class="min-h-dvh">
  <div
    class="border-accent-foreground/50 mt-16 mr-6 ml-auto w-2xs border-b border-dashed pb-2 text-end text-3xl tracking-tight lg:mr-12 lg:w-md lg:text-4xl"
  >
    ... Feed
  </div>

  {#if blogs.isLoading}
    <div class="grid grid-cols-1 gap-6 p-4 md:p-8 lg:grid-cols-2 xl:gap-10 2xl:grid-cols-3">
      {#each Array(9)}
        <Skeleton class="h-72 w-full rounded-4xl" />
      {/each}
    </div>
  {/if}

  {#if blogs.isSuccess && blogs.data.length > 0}
    <Grid blogs={blogs.data} />
  {/if}
</div>

{#if blogs.isSuccess && blogs.data.length < 1}
  <div class="mx-auto flex min-h-dvh w-3/4 items-center justify-center rounded-lg text-4xl">
    There are currently no blogs to display!
  </div>
{/if}

// apps/web/src/routes/(protected)/feed.tsx
import { createFileRoute } from "@tanstack/react-router";
import { Grid } from "@/components/grid";
import { blogsFeedQueryOptions } from "@/server/general/general.query";
import { useSuspenseQuery } from "@tanstack/react-query";

export const Route = createFileRoute("/(protected)/feed")({
  loader: async ({ context }) => {
    await context.queryClient.ensureQueryData(blogsFeedQueryOptions());
  },
  head: () => ({
    meta: [{ title: "Feed" }],
  }),
  component: RouteComponent,
});

function RouteComponent() {
  const { data: blogs } = useSuspenseQuery(blogsFeedQueryOptions());

  return (
    <>
      {blogs.length > 0 ? (
        <div className="min-h-dvh">
          <div className="mt-16 ml-auto mr-6 lg:mr-12 pb-2 w-2xs lg:w-md text-end text-3xl lg:text-4xl tracking-tight border-b border-accent-foreground/50 border-dashed">
            ... Feed
          </div>
          <Grid blogs={blogs} />
        </div>
      ) : (
        <div className="flex justify-center items-center min-h-dvh text-4xl rounded-lg w-3/4 mx-auto">
          There are currently no blogs to display!
        </div>
      )}
    </>
  );
}
