// apps/web/src/routes/(auth)/-components/forget-pass-form.tsx
import { Mail01Icon, SentIcon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { ZodError } from "zod";
import { Button } from "@/components/ui/button";
import { Field, FieldLabel } from "@/components/ui/field";
import { InputGroup, InputGroupAddon, InputGroupInput } from "@/components/ui/input-group";
import { Spinner } from "@/components/ui/spinner";
import { authClient } from "@/lib/auth-client";
import { getFirstZodError } from "@/lib/utils";
import { forgetPasswordSchema } from "@/shared/auth/auth.schema";

export const ForgetPasswordForm = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === "reset-password-complete" && e.newValue === "true") {
        localStorage.removeItem("reset-password-complete");

        navigate({ to: "/sign-in", search: { passwordChanged: true }, replace: true });
      }
    };

    window.addEventListener("storage", handleStorageChange);

    return () => window.removeEventListener("storage", handleStorageChange);
  }, []);

  const handleFormSubmit = async (e: React.SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);

    const form = new FormData(e.currentTarget);
    const email = form.get("email") as string;

    try {
      forgetPasswordSchema.parse({ email });

      const { error } = await authClient.requestPasswordReset({
        email,
        redirectTo: "/reset-password",
      });
      if (error) {
        throw new Error(error.message);
      }

      toast.success("Check your email for password reset link", {
        duration: Infinity,
        dismissible: false,
        description: "Link is valid only for 1 hour",
        descriptionClassName: "text-red-500!",
        className: "select-none",
      });
    } catch (error) {
      if (error instanceof ZodError) {
        await new Promise((resolve) => setTimeout(resolve, 800));
        toast.error(getFirstZodError(error));
      } else if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleFormSubmit} className="space-y-4">
      <Field>
        <FieldLabel htmlFor="email" className="lg:text-base">
          REGISTERED EMAIL
        </FieldLabel>
        <InputGroup className="border-0 shadow-none h-24 md:px-2 border-b rounded-none bg-transparent!">
          <InputGroupInput
            type="email"
            id="email"
            name="email"
            placeholder="Enter your registered email"
            maxLength={255}
            disabled={loading}
            required
            className="text-lg md:text-lg xl:text-2xl"
          />
          <InputGroupAddon align="inline-end">
            <HugeiconsIcon icon={Mail01Icon} className="size-7" />
          </InputGroupAddon>
        </InputGroup>
      </Field>
      <div className="flex items-center justify-end">
        <Button
          size="lg"
          type="submit"
          className="text-lg lg:text-xl h-12 xl:w-36"
          disabled={loading}
        >
          {loading ? (
            <Spinner />
          ) : (
            <>
              <HugeiconsIcon icon={SentIcon} className="size-5 mr-0.5" /> Verify
            </>
          )}
        </Button>
      </div>
    </form>
  );
};

// apps/web/src/routes/(auth)/_components/forget-pass-form.svelte
<script lang="ts">
  import { authClient } from "$lib/auth-client";
  import { Button } from "$lib/components/ui/button";
  import { Field, FieldLabel } from "$lib/components/ui/field";
  import { InputGroup, InputGroupAddon, InputGroupInput } from "$lib/components/ui/input-group";
  import { Spinner } from "$lib/components/ui/spinner";
  import { getFirstZodError } from "$lib/utils";
  import { Mail01Icon, SentIcon } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";
  import { ForgetPasswordSchema } from "@metapress/contracts/auth";
  import { toast } from "svelte-sonner";
  import { ZodError } from "zod";

  let loading = $state(false);

  const handleFormSubmit = async (e: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    e.preventDefault();
    loading = true;

    const form = new FormData(e.currentTarget);
    const email = form.get("email") as string;

    try {
      ForgetPasswordSchema.parse({ email });

      const { error } = await authClient.requestPasswordReset({
        email,
        redirectTo: `${window.location.origin}/reset-password`,
      });
      if (error) {
        throw new Error(error.message);
      }

      toast.success("Check your email for password reset link", {
        duration: Infinity,
        dismissible: false,
        description: "Link is valid only for 1 hour",
        descriptionClass: "text-red-500!",
        class: "select-none",
      });
    } catch (error) {
      if (error instanceof ZodError) {
        await new Promise((resolve) => setTimeout(resolve, 800));
        toast.error(getFirstZodError(error));
      } else if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error("Something went wrong");
      }
    } finally {
      loading = false;
    }
  };
</script>

<form onsubmit={handleFormSubmit} class="space-y-4">
  <Field>
    <FieldLabel for="email" class="lg:text-base">REGISTERED EMAIL</FieldLabel>
    <InputGroup class="h-24 rounded-none border-b bg-transparent shadow-none md:px-2">
      <InputGroupInput
        type="email"
        id="email"
        name="email"
        placeholder="Enter your registered email"
        disabled={loading}
        required
        class="text-lg md:text-lg xl:text-2xl"
      />
      <InputGroupAddon align="inline-end">
        <HugeiconsIcon icon={Mail01Icon} class="size-7" />
      </InputGroupAddon>
    </InputGroup>
  </Field>
  <div class="flex items-center justify-end">
    <Button size="lg" type="submit" class="h-12 text-lg lg:text-xl xl:w-36" disabled={loading}>
      {#if loading}
        <Spinner />
      {:else}
        <HugeiconsIcon icon={SentIcon} class="mr-0.5 size-5" /> Verify
      {/if}
    </Button>
  </div>
</form>
