// apps/web/src/components/ui/sonner.tsx
import {
  Alert02Icon,
  CheckmarkCircle02Icon,
  InformationCircleIcon,
  Loading03Icon,
  MultiplicationSignCircleIcon,
} from "@hugeicons/core-free-icons";
import { useTheme } from "next-themes";
import { Toaster as Sonner } from "sonner";
import { HugeiconsIcon } from "@hugeicons/react";

import type { ToasterProps } from "sonner";

const Toaster = ({ ...props }: ToasterProps) => {
  const { theme = "system" } = useTheme();

  return (
    <Sonner
      theme={theme as ToasterProps["theme"]}
      position="top-center"
      className="toaster group"
      icons={{
        success: <HugeiconsIcon icon={CheckmarkCircle02Icon} strokeWidth={2} className="size-4" />,
        info: <HugeiconsIcon icon={InformationCircleIcon} strokeWidth={2} className="size-4" />,
        warning: <HugeiconsIcon icon={Alert02Icon} strokeWidth={2} className="size-4" />,
        error: (
          <HugeiconsIcon icon={MultiplicationSignCircleIcon} strokeWidth={2} className="size-4" />
        ),
        loading: (
          <HugeiconsIcon icon={Loading03Icon} strokeWidth={2} className="size-4 animate-spin" />
        ),
      }}
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
          "--border-radius": "var(--radius)",
        } as React.CSSProperties
      }
      toastOptions={{
        classNames: {
          toast: "cn-toast",
        },
        style: {
          fontFamily: "Bricolage Grotesque",
          borderRadius: "calc(var(--radius-2xl)",
          fontSize: "var(--text-sm)",
          padding: "calc(var(--spacing) * 3) calc(var(--spacing) * 5)",
          gap: "calc(var(--spacing) * 2)",
        },
      }}
      {...props}
    />
  );
};

export { Toaster };

// apps/web/src/lib/components/ui/sonner/sonner.svelte
<script lang="ts">
  import { Loading03Icon } from "@hugeicons/core-free-icons";
  import { CheckmarkCircle02Icon } from "@hugeicons/core-free-icons";
  import { MultiplicationSignCircleIcon } from "@hugeicons/core-free-icons";
  import { InformationCircleIcon } from "@hugeicons/core-free-icons";
  import { Alert02Icon } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";
  import { mode } from "mode-watcher";
  import { Toaster as Sonner, type ToasterProps as SonnerProps } from "svelte-sonner";

  let { ...restProps }: SonnerProps = $props();
</script>

<Sonner
  theme={mode.current}
  position="top-center"
  class="toaster group"
  style="--normal-bg: var(--color-popover); --normal-text: var(--color-popover-foreground); --normal-border: var(--color-border);"
  toastOptions={{ class: "font-sans! rounded-4xl! px-6! text-sm!" }}
  {...restProps}
>
  {#snippet loadingIcon()}
    <HugeiconsIcon icon={Loading03Icon} strokeWidth={2} class="size-4 animate-spin" />
  {/snippet}
  {#snippet successIcon()}
    <HugeiconsIcon icon={CheckmarkCircle02Icon} strokeWidth={2} class="size-4" />
  {/snippet}
  {#snippet errorIcon()}
    <HugeiconsIcon icon={MultiplicationSignCircleIcon} strokeWidth={2} class="size-4" />
  {/snippet}
  {#snippet infoIcon()}
    <HugeiconsIcon icon={InformationCircleIcon} strokeWidth={2} class="size-4" />
  {/snippet}
  {#snippet warningIcon()}
    <HugeiconsIcon icon={Alert02Icon} strokeWidth={2} class="size-4" />
  {/snippet}
</Sonner>
